### ISSUE TITLE
Showcase your project in Beautiful Jekyll

### ISSUE THREAD

**Issue by VincentTam** [einsteinpy/blog.einsteinpy.org#355]
Have you ever thought of featuring this project at the Jekyll theme's README?

https://github.com/daattali/beautiful-jekyll/#showcased-users-success-stories

**Comment by shreyasbapat** [comment]
I have contacted the author!

**Comment by shreyasbapat** [comment]
@daattali charges some amount now! 

We are in no state to do that :)

**Comment by VincentTam** [comment]
> @daattali charges some amount now!
> 
> We are in no state to do that :)

Oh!  If I had known that, I wouldn't have started this issue at the first place.  Thanks for taking action.  Your blog would be a successful example of the theme in the mind of, at least, the team members and users of your project, and me as well.  Cheers!
