### ISSUE TITLE
Favicon for EinsteinPy blog

### ISSUE THREAD

**Issue by yashrsharma44** [einsteinpy/blog.einsteinpy.org#358]
## Favicon 
Currently, there is no favicon for **EinsteinPy** blog, so a favicon can be made for it.
![image](https://user-images.githubusercontent.com/31438680/60616879-187bf700-9df0-11e9-8cd1-34afec2eb66a.png)

## Suggestions
The favicon can be similar to the **EinsteinPy** logo.

**Comment by shreyasbapat** [comment]
Thanks @yashrsharma44 . I don't know how I missed it.

**Comment by yashrsharma44** [comment]
Better late than never 😛

**Comment by shreyasbapat** [comment]
Potentially Closed
